### ISSUE TITLE
SwiftLint part seem haven't scan for any files

### ISSUE THREAD

**Issue by leungping** [insideapp-oss/sonar-apple#65]
15:32:53.579 INFO: Sensor SwiftLint Sensor [sonarapple]
15:32:53.580 INFO: Sensor SwiftLint Sensor [sonarapple] (done) | time=1ms

seem SwiftLint doesn't scan any file with no result

However, Swift Sensor [sonarapple] logged with done and execute for 30000ms.

Any configuration missed will make SwiftLint does not work?

**Comment by gaelfoppolo** [comment]
Hi @leungping,

The plugin runs SwftLint tool using the sources (`sonar.sources`) defined in the `sonar-project.properties`. Maybe this is the issue here. Can you share your `sonar-project.properties` ?
Also, can you run again your `sonar-scanner` command by adding the argument `-X` and share the SwiftLint log part? This argument will add debug logs.

If possible, can you reformat your issue to follow the bug report template?

**Comment by leungping** [comment]
thx, it solved. 
since your properties example mentioned sonar.source defaults to "." . i just comment this property. i think it should be the cause. Thanks!
